export const cards = [
  {
    fontFormats: ["TTF", "OTF", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "5 начертаний",
    currency: "$ € £ ¥",
    category: "Гротески",
    subCategory: "Вытянутые",
    authorsTextBeforeUrl: "Free by",
    authorUrl: "https://www.fontfabric.com/fonts/bebas-neue/#font-styles",
    authorTextUrl: "Ryoichi Tsunekawa",
    color: "#272727",
    fontSize: 25,
    downloadUrl: "/fonts/BebasNeue.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "Гротески",
    subCategory: "Геометрические",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#3F1111",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "Антиквы",
    subCategory: "Переходные",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#05010F",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: ["Валют нет :("],
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#1D1103",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: ["Валют нет :("],
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#1F2020",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    name: "BebasNeue",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
];
