export const cards = [
  {
    id: 1,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "Гротески",
    subCategory: "Нейтральные",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 2,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "Гротески",
    subCategory: "Геометрические",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#3F1111",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 2,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "Антиквы",
    subCategory: "Переходные",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#05010F",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 2,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: ["Валют нет :("],
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#1D1103",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 2,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: ["Валют нет :("],
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#1F2020",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 1,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 1,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
  {
    id: 1,
    fontFormats: ["TTF", "OTF", "EOT", "WOFF", "WOFF 2"],
    image: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    variationsCount: "1 начертание",
    currency: "Валют нет :(",
    category: "С придурью",
    subCategory: "Широкие",
    authorUrl: "https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
    color: "#0A1521",
    fontSize: 25,
    downloadUrl: "/fonts/Roboto.zip",
  },
];
